import { ArrowRight, CircleAlert, Plus, ReceiptText, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useEffect, useState } from 'react'

import { Button } from '@/components/ui/button'
import { formatGroupDates, listGroups, type Group } from '@/features/groups/group-service'

export function DashboardPage() {
  const [groups, setGroups] = useState<Array<Group & { memberCount: number }>>([])
  const [loading, setLoading] = useState(true)
  useEffect(() => { let active=true; listGroups().then((data)=>active&&setGroups(data)).catch(()=>active&&setGroups([])).finally(()=>active&&setLoading(false)); return ()=>{active=false} }, [])
  return <section className="space-y-7">
    <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-primary">SplitSmart</p><h1 className="mt-1 text-3xl font-semibold tracking-tight sm:text-4xl">Your shared-money space.</h1><p className="mt-2 text-muted-foreground">Create a group to start tracking shared expenses.</p></div><Button asChild><Link to="/groups/new"><Plus className="size-4" />Create group</Link></Button></div>
    <div className="grid gap-4 md:grid-cols-3"><BalanceCard label="Groups" value={loading?'…':String(groups.length)} hint={groups.length===1?'1 shared space':'Your shared spaces'} /><BalanceCard label="Expenses" value="—" hint="Expense tracking comes next" /><BalanceCard label="Settlements" value="—" hint="Settlement tracking comes next" /></div>
    <div className="grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><section className="rounded-2xl border bg-card p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Your groups</h2><p className="mt-1 text-sm text-muted-foreground">Only groups you create or join appear here.</p></div><Button asChild size="sm" variant="ghost"><Link to="/groups">View all<ArrowRight className="size-4" /></Link></Button></div>{groups.length===0&&!loading?<div className="mt-5 rounded-xl border border-dashed p-8 text-center"><Users className="mx-auto size-6 text-muted-foreground"/><p className="mt-3 text-sm font-medium">No groups yet</p><p className="mt-1 text-sm text-muted-foreground">Create your first group to get started.</p></div>:<div className="mt-5 space-y-3">{groups.slice(0,3).map(group=><Link key={group.id} to={`/groups/${group.id}`} className="flex items-center gap-4 rounded-xl border p-4 transition hover:bg-muted/50"><span className="grid size-11 place-items-center rounded-xl bg-muted"><Users className="size-5"/></span><span className="min-w-0 flex-1"><span className="block font-medium truncate">{group.name}</span><span className="mt-0.5 block text-sm text-muted-foreground">{formatGroupDates(group)} · {group.memberCount} {group.memberCount===1?'member':'members'}</span></span><ArrowRight className="size-4 text-muted-foreground"/></Link>)}</div>}</section><section className="rounded-2xl border bg-primary p-6 text-primary-foreground shadow-sm"><span className="grid size-10 place-items-center rounded-xl bg-primary-foreground/10"><ReceiptText className="size-5"/></span><h2 className="mt-5 text-xl font-semibold">Smart Trip Mode</h2><p className="mt-2 text-sm leading-6 text-primary-foreground/75">Connect a transaction source later and SplitSmart can suggest expenses during your trip. You always approve before anything is added.</p><div className="mt-6 text-xs font-medium text-primary-foreground/80">Coming soon</div></section></div>
  </section>
}
function BalanceCard({label,value,hint}:{label:string;value:string;hint:string}){return <article className="rounded-2xl border bg-card p-5 shadow-sm"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-3 text-2xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-muted-foreground">{hint}</p></article>}
export function PlaceholderPage({title,description}:{title:string;description:string}){return <section className="rounded-xl border bg-card p-8 shadow-sm"><p className="text-sm font-medium text-primary">Coming next</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-3 max-w-2xl text-muted-foreground">{description}</p></section>}
export function NotFoundPage(){return <section className="mx-auto max-w-lg py-20 text-center"><CircleAlert className="mx-auto size-10 text-primary" aria-hidden="true"/><h1 className="mt-4 text-2xl font-semibold">Page not found</h1><p className="mt-2 text-muted-foreground">The page you requested does not exist or has moved.</p><Button asChild className="mt-6"><Link to="/">Return home <ArrowRight className="size-4"/></Link></Button></section>}
