import { ArrowLeft, CalendarDays, ChevronRight, CircleAlert, Loader2, MailPlus, Plus, Users } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'

import { Button } from '@/components/ui/button'
import { supabase } from '@/lib/supabase'
import { createGroup, formatGroupDates, getGroup, listGroupMembers, listGroups, type Group, type GroupMember } from '@/features/groups/group-service'

export function GroupsPage() {
  const [groups, setGroups] = useState<Array<Group & { memberCount: number }>>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  useEffect(() => { let active = true; listGroups().then((data) => active && setGroups(data)).catch((e: Error) => active && setError(e.message)).finally(() => active && setLoading(false)); return () => { active = false } }, [])
  return <section className="space-y-8">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-primary">Your groups</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Where shared spending happens.</h1><p className="mt-2 max-w-2xl text-muted-foreground">Trips, homes, dinners or anything you split together.</p></div><Button asChild><Link to="/groups/new"><Plus className="size-4" />Create group</Link></Button></div>
    {loading && <div className="rounded-2xl border bg-card p-8 text-center text-sm text-muted-foreground">Loading your groups…</div>}
    {error && <div role="alert" className="rounded-2xl border border-destructive/30 bg-destructive/5 p-6 text-sm text-destructive">Could not load groups: {error}</div>}
    {!loading && !error && groups.length === 0 && <div className="rounded-2xl border border-dashed bg-card p-10 text-center"><span className="mx-auto grid size-12 place-items-center rounded-xl bg-muted"><Users className="size-5" /></span><h2 className="mt-4 font-semibold">No groups yet</h2><p className="mt-1 text-sm text-muted-foreground">Create your first group and start splitting shared expenses.</p><Button asChild className="mt-5"><Link to="/groups/new"><Plus className="size-4" />Create your first group</Link></Button></div>}
    {!loading && !error && groups.length > 0 && <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{groups.map((group) => <Link key={group.id} to={`/groups/${group.id}`} className="group rounded-2xl border bg-card p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-xl bg-muted text-muted-foreground"><Users className="size-5" /></span><ChevronRight className="size-5 text-muted-foreground" /></div><h2 className="mt-5 text-lg font-semibold">{group.name}</h2><p className="mt-1 text-sm text-muted-foreground">{formatGroupDates(group)} · {group.memberCount} {group.memberCount === 1 ? 'member' : 'members'}</p><div className="mt-6 border-t pt-4"><p className="text-xs uppercase tracking-wide text-muted-foreground">Status</p><p className="mt-1 text-sm font-medium">{group.smart_trip_mode ? 'Smart Trip Mode enabled' : 'Smart Trip Mode off'}</p></div></Link>)}</div>}
  </section>
}

export function CreateGroupPage() {
  const navigate = useNavigate(); const [name,setName]=useState(''); const [currency,setCurrency]=useState('INR'); const [startDate,setStartDate]=useState(''); const [endDate,setEndDate]=useState(''); const [smartCapture,setSmartCapture]=useState(true); const [error,setError]=useState(''); const [saving,setSaving]=useState(false)
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); if (!name.trim()) return; if (startDate && endDate && startDate > endDate) { setError('Trip start date must be on or before trip end date.'); return } setSaving(true); try { const groupId=await createGroup({name,currency,tripStartDate:startDate,tripEndDate:endDate,smartTripMode:smartCapture}); navigate(`/groups/${groupId}`) } catch(e) { setError(e instanceof Error ? e.message : 'Could not create the group. Please try again.') } finally { setSaving(false) } }
  return <section className="mx-auto max-w-2xl space-y-6"><Button asChild variant="ghost" className="-ml-3"><Link to="/groups"><ArrowLeft className="size-4" />Back to groups</Link></Button><div><p className="text-sm font-semibold text-primary">New group</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Set up your shared space.</h1><p className="mt-2 text-muted-foreground">Trip dates are optional. Add them when this group is tied to a journey.</p></div><form onSubmit={handleSubmit} className="rounded-2xl border bg-card p-6 shadow-sm sm:p-8"><div className="space-y-6"><label className="block"><span className="text-sm font-medium">Group name</span><input autoFocus required value={name} onChange={(e)=>setName(e.target.value)} placeholder="e.g. Goa Getaway" className="mt-2 h-11 w-full rounded-lg border bg-background px-3 outline-none focus:ring-2 focus:ring-ring" /></label><label className="block"><span className="text-sm font-medium">Currency</span><select value={currency} onChange={(e)=>setCurrency(e.target.value)} className="mt-2 h-11 w-full rounded-lg border bg-background px-3 outline-none focus:ring-2 focus:ring-ring"><option>INR</option><option>USD</option><option>EUR</option><option>GBP</option></select></label><div><div className="flex items-center gap-2"><CalendarDays className="size-4 text-primary" /><span className="text-sm font-medium">Trip dates <span className="font-normal text-muted-foreground">(optional)</span></span></div><div className="mt-2 grid gap-3 sm:grid-cols-2"><input type="date" aria-label="Trip start date" value={startDate} onChange={(e)=>setStartDate(e.target.value)} className="h-11 rounded-lg border bg-background px-3" /><input type="date" aria-label="Trip end date" value={endDate} onChange={(e)=>setEndDate(e.target.value)} className="h-11 rounded-lg border bg-background px-3" /></div></div><label className="flex cursor-pointer items-start gap-3 rounded-xl border bg-muted/30 p-4"><input type="checkbox" checked={smartCapture} onChange={(e)=>setSmartCapture(e.target.checked)} className="mt-1 size-4 accent-primary" /><span><span className="block text-sm font-medium">Enable Smart Trip Mode</span><span className="mt-1 block text-sm text-muted-foreground">Suggestions can be added later and always require your confirmation.</span></span></label>{error && <div role="alert" className="flex gap-2 rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive"><CircleAlert className="size-4 shrink-0" />{error}</div>}</div><div className="mt-8 flex justify-end gap-3 border-t pt-6"><Button asChild type="button" variant="outline"><Link to="/groups">Cancel</Link></Button><Button type="submit" disabled={!name.trim() || saving}>{saving ? 'Creating…' : 'Create group'}</Button></div></form></section>
}

export function GroupDetailPage() {
  const { groupId }=useParams<{groupId:string}>(); const [group,setGroup]=useState<Group|null>(null); const [members,setMembers]=useState<GroupMember[]>([]); const [inviteEmail,setInviteEmail]=useState(''); const [invites,setInvites]=useState<Array<{id:string;invited_email:string;status:string}>>([]); const [loading,setLoading]=useState(true); const [inviting,setInviting]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('')
  async function loadInvites(id:string){ const {data,error:e}=await supabase.from('group_invitations').select('id,invited_email,status').eq('group_id',id).eq('status','pending').order('created_at',{ascending:false}); if(e) throw new Error(e.message); setInvites((data??[]) as Array<{id:string;invited_email:string;status:string}>) }
  useEffect(()=>{if(!groupId)return;let active=true;Promise.all([getGroup(groupId),listGroupMembers(groupId),loadInvites(groupId)]).then(([g,m])=>{if(!active)return;if(!g)setError('This group does not exist or you do not have access to it.');setGroup(g);setMembers(m)}).catch((e:Error)=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false}},[groupId])
  async function handleInvite(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!groupId||inviting)return;const email=inviteEmail.trim().toLowerCase();setError('');setMessage('');setInviting(true);try{const {data:userData}=await supabase.auth.getUser();if(!userData.user)throw new Error('Your session has expired. Please sign in again.');const {error:e}=await supabase.from('group_invitations').insert({group_id:groupId,invited_email:email,invited_by:userData.user.id});if(e)throw new Error(e.message);setInviteEmail('');setMessage(`Invite saved for ${email}.`);await loadInvites(groupId)}catch(e){setError(e instanceof Error?e.message:'Could not save the invitation.')}finally{setInviting(false)}}
  if(loading)return <section className="rounded-2xl border bg-card p-8 text-center text-sm text-muted-foreground"><Loader2 className="mx-auto size-5 animate-spin" /></section>
  if(error||!group)return <section className="space-y-4"><Button asChild variant="ghost" className="-ml-3"><Link to="/groups"><ArrowLeft className="size-4" />All groups</Link></Button><div className="rounded-2xl border border-destructive/30 bg-destructive/5 p-6 text-sm text-destructive">{error||'Group not found.'}</div></section>
  return <section className="space-y-6"><Button asChild variant="ghost" className="-ml-3"><Link to="/groups"><ArrowLeft className="size-4" />All groups</Link></Button><div className="rounded-2xl border bg-card p-6 shadow-sm sm:p-8"><p className="text-sm font-semibold text-primary">{group.smart_trip_mode?'Smart Trip group':'Shared group'}</p><h1 className="mt-1 text-3xl font-semibold">{group.name}</h1><p className="mt-2 text-muted-foreground">{formatGroupDates(group)} · {members.length} {members.length===1?'member':'members'} · {group.currency}</p><div className="mt-8 grid gap-3 sm:grid-cols-3"><Metric label="Total spent" value="—"/><Metric label="You owe" value="—"/><Metric label="You are owed" value="—"/></div></div><div className="grid gap-6 lg:grid-cols-[1.2fr_1fr]"><section className="rounded-2xl border bg-card p-6 shadow-sm"><div className="flex items-center gap-2"><Users className="size-5 text-primary"/><h2 className="font-semibold">Members</h2></div><p className="mt-1 text-sm text-muted-foreground">You are already included as the group owner.</p><div className="mt-5 space-y-3">{members.map(m=><MemberRow key={m.user_id} member={m}/>)}</div></section><section className="rounded-2xl border bg-card p-6 shadow-sm"><div className="flex items-center gap-2"><MailPlus className="size-5 text-primary"/><div><h2 className="font-semibold">Invite members</h2><p className="mt-1 text-sm text-muted-foreground">Add people by email. They can join once invitation delivery is connected.</p></div></div><form onSubmit={handleInvite} className="mt-5 space-y-3"><input type="email" required value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)} placeholder="friend@example.com" className="h-11 w-full rounded-lg border bg-background px-3 outline-none focus:ring-2 focus:ring-ring"/><Button type="submit" className="w-full" disabled={inviting}>{inviting&&<Loader2 className="size-4 animate-spin"/>}{inviting?'Saving…':'Invite member'}</Button></form>{message&&<p className="mt-3 text-sm text-primary">{message}</p>}{error&&<p className="mt-3 text-sm text-destructive">{error}</p>}{invites.length>0&&<div className="mt-6 border-t pt-5"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Pending invitations</p><div className="mt-3 space-y-2">{invites.map(i=><div key={i.id} className="flex items-center justify-between rounded-lg bg-muted/40 px-3 py-2"><span className="truncate text-sm">{i.invited_email}</span><span className="text-xs text-muted-foreground">Pending</span></div>)}</div></div>}</section></div><section className="rounded-2xl border border-dashed bg-card p-6 text-center"><p className="font-medium">Ready for expenses?</p><p className="mt-1 text-sm text-muted-foreground">Add the first expense after your members are in the group.</p><Button className="mt-4" disabled><Plus className="size-4"/>Add expense</Button></section></section>
}

function MemberRow({member}:{member:GroupMember}){const[name,setName]=useState(member.role==='owner'?'You':'Member');useEffect(()=>{let active=true;supabase.from('profiles').select('display_name').eq('id',member.user_id).maybeSingle().then(({data})=>{if(active&&data?.display_name)setName(data.display_name)});return()=>{active=false}},[member.user_id]);return <div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-muted text-sm font-semibold">{name[0]?.toUpperCase()}</span><span className="text-sm font-medium">{name}</span></div>{member.role==='owner'&&<span className="text-xs text-muted-foreground">Owner</span>}</div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-muted/50 p-4"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>}
